policy: sync
txtOwnerId: ${infra_name}
provider:
  name: ${provider}
domainFilters:
- ${domain}
serviceAccount:
  create: false
  name: ${sa_name}
  # annotations:
  #   iam.gke.io/gcp-service-account: ${sa_email}
nodeSelector:
  tenantname: ${namespace}
