name: Run TF Module Test 

on:
  workflow_call:
    inputs:
      tf_example:
        required: true
        type: string

jobs:
  tflint:
    name: TF Lint
    runs-on: ubuntu-latest
    env:
      MODULE_DIR: ./modules/${{ inputs.tf_example }}
      EXAMPLE_DIR: ./examples/${{ inputs.tf_example }}
    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    # - uses: actions/cache@v3
    #   name: Cache plugin dir
    #   with:
    #     path: ~/.tflint.d/plugins
    #     key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.44.1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Show versions
      run: |
        terraform version
        tflint --version

    - name: TF Validate Module
      uses: ./.github/actions/tf_validate
      with:
        wkdir: ${{ env.MODULE_DIR }}

    - name: TF Validate Example for Module
      uses: ./.github/actions/tf_validate
      with:
        wkdir: ${{ env.EXAMPLE_DIR }}

    - name: Plan the Example
      working-directory: ${{ env.EXAMPLE_DIR }}
      run: terraform plan
