name: Test Modules

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tf_module_test:
    name: Test
    uses: duplocloud/actions/.github/workflows/test-tf-modules.yml@main
    secrets: inherit
