name: Test Modules

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  test_modules:
    name: Test Modules
    uses: ./.github/workflows/module_test.yml
    secrets: inherit
    strategy:
      matrix:
        module:
        - cert-manager
        - github-actions-controller
        - gitlab-runner
        # - circleci-runner
        # - keda
        # - rabbitmq-operator
    with:
      module_name: ${{ matrix.module }}
