name: Test Modules

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  gha_example:
    name: Github Actions Controller
    uses: ./.github/workflows/example.yml
    with:
      tf_example: github-actions-controller
